package com.github.divideby0.spotfire

import org.optaplanner.core.api.score.buildin.bendable.BendableScoreHolder;
import com.github.divideby0.spotfire.domain.*;
import java.util.List;
import java.util.Set;
import com.wrapper.spotify.enums.Modality;
//import com.github.divideby0.spotfire.solver.TransitionUtils;

global BendableScoreHolder scoreHolder;

rule "set tempo change"
    no-loop
    when
    $pt: PlaylistTrack(
        track != null,
        previousTrack != null,
        tempoChange != track.startTempo - previousTrack.endTempo,
        $change: track.startTempo - previousTrack.endTempo
    )

    then
    $pt.setTempoChange($change);
    update($pt);
end

rule "tempo change should not exceed 30 bpm"
    when
    PlaylistTrack(
        $maxPosition: position,
        $minPosition: position - 3
    )
    $averageChange: Number(doubleValue() > 30.0) from accumulate(
        PlaylistTrack(
            track != null,
            position <= $maxPosition,
            position > $minPosition,
            $tempoChange: Math.abs(tempoChange)
        ),
        average($tempoChange)
    )

    then
    Integer penalty = Double.valueOf((30 - $averageChange.doubleValue()*10)).intValue();
    scoreHolder.addSoftConstraintMatch(kcontext, 3, penalty);
end